runtime: ruby25
entrypoint: bundle exec ruby app.rb
service: default

env_variables:
  RAILS_ENV: production
  MAX_THREADS: 5
  MIN_THREADS: 5

handlers:
  - url: /.*
    secure: always
    script: auto